import type { Axeom } from "@axeom/core";

export interface SwaggerOptions {
  /**
   * Path to the OpenAPI JSON specification.
   * @default "/swagger.json"
   */
  path?: string;
  /**
   * Path to the Swagger UI documentation page.
   * @default "/docs"
   */
  uiPath?: string;
  /**
   * API Information.
   */
  info?: {
    title?: string;
    version?: string;
    description?: string;
  };
}

/**
 * Axeom Swagger Plugin.
 * Generates an OpenAPI 3.0 spec and provides a Scalar documentation UI.
 */
export const swagger = (options: SwaggerOptions = {}) => {
  const info = {
    title: "Axeom API Documentation",
    version: "1.0.0",
    description: "Interactive API documentation generated by @axeom/swagger",
    ...options.info,
  };
  const swaggerPath = options.path || "/swagger.json";
  const uiPath = options.uiPath || "/docs";

  return <T extends Record<string, any>, D extends Record<string, any>>(
    app: Axeom<T, D>,
  ) => {
    app.get(swaggerPath, ({ request }) => {
      const routes = app.router.getRoutes();
      const paths: any = {};

      const url = new URL(request.url);
      const basePath =
        request.headers.get("X-Axeom-Base") ||
        url.pathname.replace(swaggerPath, "") ||
        "/";

      routes.forEach((route) => {
        // ... rest of path conversion logic ...
        const path = route.path.replace(/:(\w+)/g, "{$1}");
        const method = route.method.toLowerCase();

        if (!paths[path]) paths[path] = {};

        paths[path][method] = {
          summary: route.schema?.summary || `${route.method} ${route.path}`,
          description: route.schema?.description,
          tags: route.schema?.tags || [route.path.split("/")[1] || "default"],
          parameters: [] as any[],
          responses: {
            200: {
              description: "Successful response",
              content: {
                "application/json": {
                  schema: { type: "object" },
                },
              },
            },
            400: {
              description: "Validation error",
            },
          },
        };

        const op = paths[path][method];

        if (route.schema?.query) {
          const querySchema = (route.schema.query as any).toJSONSchema();
          if (querySchema.properties) {
            Object.entries(querySchema.properties).forEach(
              ([name, schema]: [any, any]) => {
                op.parameters.push({
                  name,
                  in: "query",
                  required: querySchema.required?.includes(name),
                  schema,
                });
              },
            );
          }
        }

        route.paramNames.forEach((name) => {
          op.parameters.push({
            name,
            in: "path",
            required: true,
            schema: { type: "string" },
          });
        });

        if (route.schema?.body && ["post", "put", "patch"].includes(method)) {
          op.requestBody = {
            content: {
              "application/json": {
                schema: (route.schema.body as any).toJSONSchema(),
              },
            },
          };
        }
      });

      return {
        openapi: "3.1.0",
        info,
        servers: [{ url: basePath }],
        paths,
      };
    });

    // Scalar UI Documentation Route
    app.get(uiPath, () => {
      return new Response(
        `<!doctype html>
    <html>
      <head>
        <title>${info.title}</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <!-- Scalar Web Component -->
        <script
          id="api-reference"
         
          data-url="${swaggerPath}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
      </body>
    </html>`,
        { headers: { "Content-Type": "text/html" } },
      );
    });

    return app;
  };
};

export default swagger;

//  //  data-url="${swaggerPath.startsWith("/") ? swaggerPath.slice(1) : swaggerPath}"></>
